version: 2.1

jobs:
  uptime-check:
    docker:
      - image: cimg/node:20.0
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Run Uptime Check Script
          command: node scripts/uptime-check.js

workflows:
  scheduled-uptime-check:
    triggers:
      - schedule:
          cron: "0 * * * *"       # Every hour (UTC)
          filters:
            branches:
              only: main
      - schedule:
          cron: "30 19 * * *"     # 1:00 AM IST
          filters:
            branches:
              only: main
      - schedule:
          cron: "30 23 * * *"     # 5:00 AM IST
          filters:
            branches:
              only: main
      - schedule:
          cron: "30 5 * * *"      # 11:00 AM IST
          filters:
            branches:
              only: main
      - schedule:
          cron: "30 8 * * *"      # 2:00 PM IST
          filters:
            branches:
              only: main
    jobs:
      - uptime-check
